'---------------------------------------------------------------------
' Generated by Micro Focus Reflection Desktop (17.0.434.0)
' Generated by the Macro Recorder on 10/13/2021 6:02:42 PM
'---------------------------------------------------------------------
' Common variable declarations
Dim ibmCurrentTerminal As IbmTerminal
Dim ibmCurrentScreen As IbmScreen
Dim hiddenTextEntry As String
Dim returnValue As Integer
Dim timeout As Integer
Dim waitText As String
Dim dataText As String
timeout = 15000

Set ibmCurrentTerminal = ThisFrame.SelectedView.control
Set ibmCurrentScreen = ibmCurrentTerminal.screen
'---------------------------------------------------------------------
ibmCurrentScreen.SendControlKey (ControlKeyCode_Clear)
'


returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
ibmCurrentScreen.SendKeys ("ea")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'


returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("eb")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'


returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("ec")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'


returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("ed")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'



returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("ee")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'



returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("bn")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'


stopText = "DATA"

returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)

While ibmCurrentScreen.GetText(22, 20, 4) <> data
    returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
    ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
    returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
EndWhile




ibmCurrentScreen.SendControlKey (ControlKeyCode_Clear)
ibmCurrentScreen.SendKeys ("echl")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)


ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 1, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 8)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT:"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 8)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT:"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 8)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT:"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("echl")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 1)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 8, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Clear)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 1, 1)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendKeys ("cmm")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 7)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 7)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("cmc")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 7)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("nl")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 2)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendKeys ("bnp")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 23, 8)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
waitText = "NEXT:"
returnValue = ibmCurrentScreen.WaitForText1(timeout, waitText, 23, 2, TextComparisonOption_MatchCase)
ibmCurrentScreen.SendKeys ("py")
ibmCurrentScreen.SendControlKey (ControlKeyCode_Transmit)
'
returnValue = ibmCurrentScreen.WaitForKeyboardEnabled(timeout, 0)
'Wait for cursor to be in position before continuing
returnValue = ibmCurrentScreen.WaitForCursor1(timeout, 7, 6)
If (returnValue <> ReturnCode_Success) Then
    Err.Raise 5001, "WaitForCursor1", "Timeout waiting for cursor position.", "VBAHelp.chm", "5001"
End If
ibmCurrentScreen.SendControlKey (ControlKeyCode_Clear)
'

